---
services:
  kali-linux:
    image: lscr.io/linuxserver/kali-linux:latest
    container_name: kali-linux
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./data:/config
    ports:
      - 3550:3000
      - 3551:3001
    shm_size: "4gb"
    restart: unless-stopped